### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by ACGaming**

### CODE REVIEW

**Comment by halvors** [comment]
@ACGaming Thanks for doing this, if it's ok with you i'll hold off a little bit until i'm sure the english transaltions is done.

**Comment by ACGaming** [comment]
Sure thing.

**Comment by halvors** [comment]
@ACGaming I've decided to now merge this, but one thing needs to be updated first.

The string "item.nuclearphysics.cell.tooltip=Contains: %d" needs to be localized. Mark that "%d" is the fluid the cell is containing and already has translations from the "fluid.*" string.

So i just need a proper german translation for "Contains".

**Comment by ACGaming** [comment]
That would be "item.nuclearphysics.cell.tooltip=Enthält: %d" but that's already in the translated strings.

**Pull request merged**
